image: alpine:latest

pages:
  stage: deploy
  before_script:
  - 'command -v ssh-agent >/dev/null || ( apk update && apk add openssh-client rsync )' 
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -p 2296 $VM_IPADDRESS >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  artifacts:
    paths:
    - public
  only:
    - develop
  script:
    #- echo "the project directory is - $CI_PROJECT_DIR"
    #- cat $CI_PROJECT_DIR/README.md ; echo
    - echo "and where am I? - $PWD"